### ISSUE TITLE
module MixGleam is not available

### ISSUE THREAD

**Issue by phaleth** [gleam-lang/mix_gleam#15]
Is there any way to install MixGleam in an unattended mode? I keep getting a prompt when deploying with docker.

```sh
...
Step 7/29 : RUN git clone https://github.com/gleam-lang/mix_gleam.git --branch v0.4.0 &&     cd mix_gleam &&     MIX_ENV=prod mix do archive.build, archive.install &&     cd ..
 ---> Running in 54e3b72a4ea0
Cloning into 'mix_gleam'...
Note: switching to '419c5812e44bf63a41a9d2115bbf6e8e7f7a4019'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Compiling 9 files (.ex)
Generated mix_gleam app
Generated archive "mix_gleam-0.4.0.ez" with MIX_ENV=prod
Are you sure you want to install "mix_gleam-0.4.0.ez"? [Yn] 
...
...
...
Step 17/29 : RUN mix deps.get --only prod
 ---> Running in 3415cd3a2c5b
warning: function aliases/0 is unused
  mix.exs:68

** (UndefinedFunctionError) function MixGleam.add_aliases/0 is undefined (module MixGleam is not available)
    MixGleam.add_aliases()
    mix.exs:13: TpPhx.MixProject.project/0
    (mix 1.13.2) lib/mix/project.ex:827: Mix.Project.get_project_config/1
    (mix 1.13.2) lib/mix/project.ex:141: Mix.Project.push/3
    (stdlib 3.17) lists.erl:1267: :lists.foldl/3
ERROR: Service 'phoenix' failed to build : The command '/bin/sh -c mix deps.get --only prod' returned a non-zero code: 1
```

**Comment by lpil** [comment]
I think `mix archive.install` accepts a `--force` flag which won't ask for confirmation

**Comment by phaleth** [comment]
Adding `--force` flag made the installation work. Thank you, Louis.
